### ISSUE TITLE
Views for Daoshboard Portals

### ISSUE THREAD

**Issue by novatell** [jdanylko/Tuxboard.Core#1]
Nice to see you. Do you having view for the dashboard samples.

**Comment by jdanylko** [comment]
Hey novatell, I'm currently in the middle of splitting this [repository](https://github.com/jdanylko/tuxboard) apart into a Core (server-side) and a client.

I did ask some of the users [what they thought about this approach](https://github.com/jdanylko/Tuxboard/issues/6).

Chime in if you'd like. I'd be interested to find out how you'd use it as well. :-)

**Comment by jdanylko** [comment]
Important: I am currently closing this repository since the examples will be contained in the [Tuxboard](https://github.com/jdanylko/Tuxboard) repository now.
